config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home' # => root_path
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      # /users/:id/ ...
      get :following, :followers
      # GET /users/1/following => following action
      # GET /users/1/followers => followers action
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.microposts
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_micropost_form.html.haml
= form_for(@micropost) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-primary"
  %span.picture
    = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'
:javascript
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 1) {
      alert('Maximum file size is 1MB. Please choose a smaller file.');
    }
  });

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => "#{following_user_path(@user)}"}
    %strong#following.stat
      = @user.following.count
    following
  %a{:href => "#{followers_user_path(@user)}"}
    %strong#followers.stat
      = @user.followers.count
    followers

app/views/shared/_user_info.html.haml
= link_to gravatar_for(current_user, size: 50), current_user
%h1= current_user.name
%span= link_to "view my profile", current_user
%span= pluralize(current_user.microposts.count, "micropost")